spring:
  profiles: dev
attributes:
  links:
    patreon:
      -1:
        rank: 3
      1:
        rank: 4
        roleIds:
          - 374985815593451521
      2:
        rank: 4
        group: 1
        roleIds:
          - 374985738296623116
      3:
        rank: 5
        group: 2
        roleIds:
          - 374985674023108609